steps:
  # Passo 1: Garantir que o script do Gradle tem permissão de execução
  - name: 'ubuntu'
    args: ['chmod', '+x', './gradlew']

  # Passo 2: Baixar o arquivo .jks do seu bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://droptvappbuild/droptv-production.jks ./app/production.jks

  # Passo 3: Executar a compilação gerando o App Bundle (.aab) de produção assinado
  - name: 'ghcr.io/cirruslabs/android-sdk:34'
    entrypoint: 'bash'
    env:
      - 'KEYSTORE_FILE=production.jks'
      - 'KEYSTORE_PASSWORD=$_KEYSTORE_PASSWORD'
      - 'KEY_ALIAS=$_KEY_ALIAS'
      - 'KEY_PASSWORD=$_KEY_PASSWORD'
    args:
      - '-c'
      - |
        yes | sdkmanager --licenses
        # Altera de assembleRelease para bundleRelease
        ./gradlew bundleRelease

# Passo 4: Exportar o arquivo .aab gerado para o bucket
artifacts:
  objects:
    location: 'gs://droptvappbuild/droptv-production-builds/$BUILD_ID/'
    # O Gradle salva o bundle em uma pasta diferente ('outputs/bundle/release/')
    paths: ['app/build/outputs/bundle/release/*.aab']

options:
  logging: CLOUD_LOGGING_ONLY